name: 'AWS Command Line Interface'
description: 'GitHub Action with the latest AWS CLI in Docker, enabling execution of AWS CLI commands.'

runs:
  using: 'docker'
  image: 'docker://amazon/aws-cli:latest'

branding:
  icon: "terminal"
  color: 'orange'
